name: Deployment Workflow
on:
  push:
    branches: [ main ]

jobs:
  API_Updation:
    name: API Updating
    runs-on: ubuntu-latest
    steps:
    - name: ssh test
      uses: appleboy/ssh-action@master
      with:
        host: 66.42.42.229
        username: main-user
        key: ${{ secrets.DEPLOY_KEY}}
        port: 22
        script: |
          screen -S f_api -X stuff "^C\n"
          screen -S f_api -X stuff "curl -O https://raw.githubusercontent.com/Govind-S-B/smart_menu_prototype_tools/main/Protores/main.py && python3 main.py ^M"
  Build_Web:
    name: Flutter Web Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd ./Protores/restt/
      - run: ls
