name: Deployment Workflow
on:
  push:
    branches: [ main ]

jobs:

  API_Updation:
    name: API Server Updation
    runs-on: ubuntu-latest
    steps:
    - name: ssh action
      uses: appleboy/ssh-action@master
      with:
        host: 66.42.42.229
        username: main-user
        key: ${{ secrets.DEPLOY_KEY}}
        port: 22
        script: |
          screen -S f_api -X stuff "^C\n"
          screen -S f_api -X stuff "curl -O https://raw.githubusercontent.com/Govind-S-B/smart_menu_prototype_tools/main/Protores/main.py && python3 main.py ^M"
          
  Build_Web:
    name: Flutter Web Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: |
          cd ./Protores/restt/
          flutter pub get
          flutter build web
          
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }} 
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p 22 -H 66.42.42.229  >> ~/.ssh/known_hosts
        
      - name: Deploy with rsync
        run: rsync -avz ./Protores/restt/build/web/ main-user@66.42.42.229:./web_build
        
  WebApp_Updation:
    name: WebApp Server Updating
    needs: Build_Web
    runs-on: ubuntu-latest
    steps:
    - name: ssh action
      uses: appleboy/ssh-action@master
      with:
        host: 66.42.42.229
        username: main-user
        key: ${{ secrets.DEPLOY_KEY}}
        port: 22
        script: |
          screen -S f_webApp -X stuff "^C\n"
          screen -S f_webApp -X stuff "python3 -m http.server 8000^M"
